const CONFIG = {
    titleWeb: "Love❤",
    introTitle: 'Miêu❤',
    introDesc: `Chúc em sinh nhật vui vẻ nha 😁`,
    btnIntro: 'Bấm đi^^',
    title: 'Cho anh hỏi cái này nha 😋. Nhớ thật lòng nha 🥰. Nếu được thì ghi màn hình nha 🤗',
    desc: 'Cho a xin phép bảo vệ e từ giờ về sau nha 💑 ',
    btnYes: 'Được nha <3',
    btnNo: 'Không nha :(((',
    question: 'A vui lắm á! Mời công chúa ban thánh chỉ 🥰',
    btnReply: 'Gửi cho Cọp <3',
    reply: 'A mà lm e buồn thì xác định nha ',
    mess: 'Vâng ạ! Cọp ngoan lắm ạ 😘😘😘',
    messDesc: 'Chúc bé sinh nhật vui vẻ nha.',
    btnAccept: '❤❤❤',
   }
